NWTServis/TextITMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using ServisTextIT.Models;
using System.Net.Mail;


namespace TextITMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            
            return View();
        }
        // GET:/Home/
        public ActionResult Korisnici()
        {
            List<Korisnik> l = new List<Korisnik>();
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:3106/");
            client.DefaultRequestHeaders.Accept.Add(
                new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = client.GetAsync("api/korisnik").Result;
            if (response.IsSuccessStatusCode)
            {

                l = response.Content.ReadAsAsync<List<Korisnik>>().Result;
            }
            return View(l);
        }
        public ActionResult Login()
        {
              return View();
        }
        public ActionResult ResetPass()
        {
            return View();
        }

        //funkcija za slanje maila
        private void SendRegistrationMail(string mailTo)
        {
            string link = "http://localhost:36729/Registration/confirmregistration";

            MailMessage msg = new MailMessage();

            msg.From = new MailAddress("sgrosic1@gmail.com");
            msg.To.Add(new MailAddress(mailTo));
            msg.Body = "Potvrdite Vašu novu lozinku, kliknite<a href=" + link + ">ovdje</a>!";
            msg.Subject = "Potvrda lozinke";
            msg.IsBodyHtml = true;

            SmtpClient smtpClient = new SmtpClient("smtp.gmail.com", Convert.ToInt32(587));
            smtpClient.Credentials = new System.Net.NetworkCredential("sgrosic1", "88aida19");
            smtpClient.EnableSsl = true;
            smtpClient.Send(msg);
        }



    }
}

NWTServis/TextITMVC/Controllers/KorisnikController.cs
using Newtonsoft.Json;
using ServisTextIT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace TextITMVC.Controllers
{
    public class KorisnikController : Controller
    {



        HttpClient client;
        //The URL of the WEB API Service
        string url = "http://localhost:3106/api/korisnik";

        //The HttpClient Class, this will be used for performing 
        //HTTP Operations, GET, POST, PUT, DELETE
        //Set the base address and the Header Formatter
        public KorisnikController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri(url);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        // GET: EmployeeInfo
        public async Task<ActionResult> Index()
        {
            HttpResponseMessage responseMessage = await client.GetAsync(url);
            if (responseMessage.IsSuccessStatusCode)
            {
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;

                var Employees = JsonConvert.DeserializeObject<List<Korisnik>>(responseData);

                return View(Employees);
            }
            return View("Error");
        }


        public ActionResult Create()
        {
            return View(new Korisnik());
        }

        //The Post method
        [HttpPost]
        public async Task<ActionResult> Create(Korisnik Emp)
        {

            HttpResponseMessage responseMessage = await client.PostAsJsonAsync(url, Emp);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Error");
        }

        public async Task<ActionResult> Edit(int id)
        {
            HttpResponseMessage responseMessage = await client.GetAsync(url + "/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;

                var Employee = JsonConvert.DeserializeObject<Korisnik>(responseData);

                return View(Employee);
            }
            return View("Error");
        }

        //The PUT Method
        [HttpPost]
        public async Task<ActionResult> Edit(int id, Korisnik Emp)
        {

            HttpResponseMessage responseMessage = await client.PutAsJsonAsync(url + "/" + id, Emp);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Error");
        }

        public async Task<ActionResult> Delete(int id)
        {
            HttpResponseMessage responseMessage = await client.GetAsync(url + "/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;

                var Employee = JsonConvert.DeserializeObject<Korisnik>(responseData);

                return View(Employee);
            }
            return View("Error");
        }

        //The DELETE method
        [HttpPost]
        public async Task<ActionResult> Delete(int id, Korisnik Emp)
        {

            HttpResponseMessage responseMessage = await client.DeleteAsync(url + "/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Error");
        }

        public ActionResult MojProfil()
        {
            return View();
        }

        //funkcija za slanje maila za reset pass
        private void SendRegistrationMail(string mailTo)
        {
            string link = "http://localhost:36729/Korisnik/confirmregistration"; // izmijeniti link

            MailMessage msg = new MailMessage();

            msg.From = new MailAddress("sgrosic1@gmail.com");
            msg.To.Add(new MailAddress(mailTo));
            msg.Body = "Za izmjenu šifre kliknite na sljedeći <a href=" + link + ">link.</a> ";
            msg.Subject = "Izmjena šifre";
            msg.IsBodyHtml = true;

            SmtpClient smtpClient = new SmtpClient("smtp.gmail.com", Convert.ToInt32(587));
            smtpClient.Credentials = new System.Net.NetworkCredential("sgrosic1", "88aida19");
            smtpClient.EnableSsl = true;
            smtpClient.Send(msg);
        }

        //akcija za slanje korisnika na novi View kada klikne link za potvrdu izmjene lozinke
        public async Task<ActionResult> confirmregistration()
        {
           
               return View("~/Views/Korisnik/Izmjena.cshtml");         

        }

        //akcija za izmjenu nove lozinke 
        public async Task<ActionResult> IzmijeniLozinku(FormCollection collection)
        {
            int userId = Convert.ToInt32(Session["id"].ToString());
            string nova = collection.Get("sifra").ToString();
            HttpResponseMessage responseMessage = await client.GetAsync(url + "/" + userId);
            if (responseMessage.IsSuccessStatusCode)
            {
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;
                var korisnik = JsonConvert.DeserializeObject<Korisnik>(responseData);
                if (korisnik != null)
                {
                    korisnik.sifra = nova; 
                    HttpResponseMessage responseMessage1 = await client.PutAsJsonAsync(url + "/" + userId, korisnik);
                    if (responseMessage1.IsSuccessStatusCode)
                    {
                        return View("~/Views/Korisnik/Uspjesno.cshtml");
                    }
                }
                else return View("~/Views/Korisnik/Neuspjesno.cshtml");

            }
            return View("Error");
        }



        public ActionResult Izmjena()
        {
            return View(new Korisnik());
        }

        public ActionResult Reset()
        {
            return View(new Korisnik());
        }

        //akcija za pronalazak korisnika putem mail-a, te pozivanje funkcije za slanje mail-a
        public async Task<ActionResult> ResetAction(FormCollection collection)
        {
            HttpResponseMessage responseMessage = await client.GetAsync(url);
            if (responseMessage.IsSuccessStatusCode)
            {
                string email = collection.Get("email").ToString(); 
                //var responseData = responseMessage.Content.ReadAsStringAsync().Result;
                List<Korisnik> l = await responseMessage.Content.ReadAsAsync<List<Korisnik>>();
                //var Employees = JsonConvert.DeserializeObject<List<Korisnik>>(responseData); // lista korisnika
                Korisnik m = l.Find(k => k.email.ToString() == email); // pronalazi korisnika s mail-om koji smo mu proslijedili
                Session["id"] = m.korisnikID;
                SendRegistrationMail(email); // šalje mu mail

                return View("~/Views/Korisnik/Provjeri.cshtml");
            }
            return View("Error");

        }
        



    }
}

NWTServis/TextITMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NWTServis/TextITMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NWTServis/TextITMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "TextIT";
}

<div style="background-color:black">
    <div ng-controller="Tekst" data-ng-init="getTekstovi()" style="background-color:black">
        <br />
        <div title="Tekstovi">
            <br />
            <p style="align-content:center; font-style:oblique; text-decoration:dashed; font-weight:900; font-size:25px; color:orangered">{{ "DOBRODOSLI" | translate }}</p>
            <hr />
            <div ng-repeat="tekst in tekstovi | startFrom: (currentPage - 1) * pageSize| limitTo: pageSize" class="jumbotron">
                <input ng-model="tekst.tekstID" style="visibility:hidden" />
                <table class="table" style="width:1020px; border-width:3px; border-collapse:collapse">
                    @*Izmjena*@
                    <tr>
                        <td>
                            <label style="font-size: 20px; color: orangered">{{tekst.naslov}}</label>
                        </td>
                    </tr>
                    <br />
                    <tr>
                        <td>
                            <p style="font-size: 15px; color: black" ng-model="tekst">{{tekst.sadrzaj}}</p>
                        </td>
                    </tr>

                </table>
                <br />
                <div style=" font-style: italic; font-size: 20px; display:block;" >
                    <div style="text-align: left; display: inline-block; font-size: 12px; color: black; font-style: italic">Objavio/la: {{tekst.korisnikID}}</div>

                    <button style=" float:right; display: inline-block;"  id="dodajkomentar" type="button" ng-click="createKomentar(tekst.tekstID)" class="btn btn-primary btn-large" ng-model="dodaj">Komentari</button>
                </div>

            </div>
            <div style="align-content: center; color: black">
                <uib-pagination boundary-links="true" total-items="totalItems" ng-model="currentPage" ng-change="pageChanged()" items-per-page="itemsPerPage"></uib-pagination>
                <pre>Trenutno ste na stranici: {{currentPage}}</pre>

            </div>


        </div>

    </div>
</div>

    <script>

        var tipKorisnika = sessionStorage.getItem("tipKorisnika");
        if (tipKorisnika == "admin") {
            document.getElementById('dodajKomentar').style.visibility = 'visible';
        }
        else if (tipKorisnika == "User") {
            document.getElementById('dodajKomentar').style.visibility = 'visible';
        }
        else {
            document.getElementById('dodajKomentar').style.visibility = 'hidden';
        }

    </script>

NWTServis/TextITMVC/Views/Home/Korisnici.cshtml
@model IEnumerable<TextITMVC.Korisnik>

@{
    ViewBag.Title = "Korisnici";
}

<h2>Korisnici</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prezime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.korisnickoIme)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.sifra)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tipKorisnika)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.prezime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.korisnickoIme)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.sifra)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tipKorisnika)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.korisnikID }) |
            @Html.ActionLink("Details", "Details", new { id=item.korisnikID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.korisnikID })
        </td>
    </tr>
}

</table>

NWTServis/TextITMVC/Views/Home/Login.cshtml
@model ServisTextIT.Models.Korisnik

@{
    ViewBag.Title = "Login";
}

<h2>{{ "PRIJAVA" | translate }}</h2>
<h4>{{ "LOGIN" | translate }}</h4>
<hr />

<div ng-controller="Login">
    <a id="reg" href="/Registration/RegisterUser"> {{ "REGSE" | translate }} </a>
    <br />
    <br />
    <label for="username">Korisničko ime</label>
    <input type="text" name="username" id="username" class="form-control" ng-model="LoginPodaci.Username" required />
    <span ng-show="form.username.$dirty && form.username.$error.required" class="help-block">Korisnicko ime je obavezno!</span>
    <br />
    <label for="password">Šifra</label>
    <input type="password" name="password" id="password" class="form-control" ng-model="LoginPodaci.Password" required />
    <span ng-show="form.password.$dirty && form.password.$error.required" class="help-block">Šifra je obavezna!</span>

    <br/>
    <button ng-disabled=" form.$invalid || vm.dataloading" class="btn btn-primary" ng-click="Login()">Login</button>
   
</div>
<br />

@Html.ActionLink("Zaboravili ste sifru?", "Reset", "Korisnik")



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NWTServis/TextITMVC/Views/Home/ResetPass.cshtml
@model ServisTextIT.Models.Korisnik

@{
    ViewBag.Title = "ResetPass";
}

<h2>ResetPass</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.sifra, "Stara sifra:", new { @class = "control-label col-md-2" })
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.sifra)
                @Html.ValidationMessageFor(model => model.sifra)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.sifra, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sifra)
                @Html.ValidationMessageFor(model => model.sifra)
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Promijenite sifru" class="btn btn-default" />
                
            </div>
        </div>
    </div>
}