NWTServis/TextITMVC/Models/Tekst.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ServisTextIT.Models
{
    [Table(name: "Tekstovi")]
    public class Tekst
    {
        public int tekstID { get; set; }
        [DisplayName("Naslov:")]
        [Required(ErrorMessage = "Niste unijeli naslov teksta !")]
        public string naslov { get; set; }
        [DisplayName("Sadržaj:")]
        [Required(ErrorMessage = "Niste unijeli sadržaj !")]
        public string sadrzaj { get; set; }
        public string link { get; set; }
        public int like { get; set; }
        public DateTime datumObjave { get; set; }
        public List<HashTag> HashTag { get; set; }
        public List<Komentar> komentari { get; set; }
        public List<Ocjena> ocjene { get; set; }
        public int korisnikID { get; set; }
        public virtual Korisnik korisnik { get; set; }
        public byte[] file { get; set; }

    }
}

NWTServis/TextITMVC/Controllers/TekstController.cs
using Newtonsoft.Json;
using ServisTextIT.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using TextITMVC.Models;

namespace TextITMVC.Controllers
{
    public class TekstController : Controller
    {



        HttpClient client;
        //The URL of the WEB API Service
        string url = "http://localhost:3106/api/tekst";

        //The HttpClient Class, this will be used for performing 
        //HTTP Operations, GET, POST, PUT, DELETE
        //Set the base address and the Header Formatter
        public TekstController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri(url);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        // GET: EmployeeInfo
        public async Task<ActionResult> Index()
        {
            HttpResponseMessage responseMessage = await client.GetAsync(url);
            if (responseMessage.IsSuccessStatusCode)
            {
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;

                var Employees = JsonConvert.DeserializeObject<List<Tekst>>(responseData);

                return View(Employees);
            }
            return View("Error");
        }

        public ActionResult Create()
        {
            return View(new Tekst());
        }

        //The Post method
        [HttpPost]
        public async Task<ActionResult> Create(Tekst Emp)
        {

            HttpResponseMessage responseMessage = await client.PostAsJsonAsync(url, Emp);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Error");
        }

        public async Task<ActionResult> Edit(int id)
        {
            HttpResponseMessage responseMessage = await client.GetAsync(url + "/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;

                var Employee = JsonConvert.DeserializeObject<Tekst>(responseData);

                return View(Employee);
            }
            return View("Error");
        }

        //The PUT Method
        [HttpPost]
        public async Task<ActionResult> Edit(int id, Tekst Emp)
        {

            HttpResponseMessage responseMessage = await client.PutAsJsonAsync(url + "/" + id, Emp);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Error");
        }

        public async Task<ActionResult> Delete(int id)
        {
            HttpResponseMessage responseMessage = await client.GetAsync(url + "/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;

                var Employee = JsonConvert.DeserializeObject<Tekst>(responseData);

                return View(Employee);
            }
            return View("Error");
        }

        //The DELETE method
        [HttpPost]
        public async Task<ActionResult> Delete(int id, Tekst Emp)
        {

            HttpResponseMessage responseMessage = await client.DeleteAsync(url + "/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Error");
        }


         //akcija za dijagram - broj tekstova po danima
        public async Task<ActionResult> KorisnikBrojTekstova()
        {
            List<MojaLista> t = new List<MojaLista>();
            HttpResponseMessage responseMessage = await client.GetAsync(url); // pokupi sve tekstove
            string url1 = "http://localhost:3106/api/korisnik";
            HttpResponseMessage responseMessage1 = await client.GetAsync(url1); // pokupi sve korisnike
            if (responseMessage.IsSuccessStatusCode && responseMessage1.IsSuccessStatusCode)
            {
                //sve tekstove smjesti u listu te
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;
                var Tekstovi = JsonConvert.DeserializeObject<List<Tekst>>(responseData);
                List<Tekst> te = await responseMessage.Content.ReadAsAsync<List<Tekst>>();

                // sve korisnike smjesti u listu ko
                var responseData1 = responseMessage1.Content.ReadAsStringAsync().Result;
                var Korisnici = JsonConvert.DeserializeObject<List<Korisnik>>(responseData1);
                List<Korisnik> ko = await responseMessage1.Content.ReadAsAsync<List<Korisnik>>();

                //kreiramo MojaLista - sastoji se iz korisnika i brojaca njegovih tekstova
                
                for (int i = 0; i < ko.Count; i++)
                {
                    int idKo = ko[i].korisnikID;
                    int brojac = 0;
                    foreach (Tekst m in te)
                    {
                        if (m.korisnikID == idKo)
                        {
                            brojac++;
                        }
                    }
                    MojaLista var = new MojaLista(ko[i], brojac);
                    t.Add(var);
                }

            }

            List<String> idList = new List<String>();
            List<int> brojacList = new List<int>();
            foreach(MojaLista l in t)
            {
                idList.Add(l.K.korisnickoIme);
                brojacList.Add(l.Brojac);
            }
           
            IEnumerable<String> resultid = idList.ToList();
            IEnumerable<int> resulttekst = brojacList.ToList();
            
            var key = new Chart(width: 550, height: 350)
            
            .AddTitle("Broj tekstova po korisniku")
            .AddSeries(
                chartType: "bar",
               // legend: "Rainfall",
                name: "Sabinaaa",
                xValue: resultid, xField: "KORISNIK",
                yValues: resulttekst, yFields: "TEKST")
               
            .Write();               
           

            return null;
        }

        public ActionResult Dijagram()
        {
            return View();
        }

        //akcija za dijagram - broj korisnika, broj tekstova, broj komentara

        public async Task<ActionResult> PitaDijagram()
        {
           
            HttpResponseMessage responseMessage = await client.GetAsync(url); // pokupi sve tekstove
            string url1 = "http://localhost:3106/api/korisnik";
            HttpResponseMessage responseMessage1 = await client.GetAsync(url1); // pokupi sve korisnike
            string url2 = "http://localhost:3106/api/komentar";
            HttpResponseMessage responseMessage2 = await client.GetAsync(url2);
            int brojtekstova = 0;
            int brojkorisnika = 0;
            int brojkomentara = 0;
            List<String> ln = new List<String>();
            List<int> br = new List<int>();

            if (responseMessage.IsSuccessStatusCode && responseMessage1.IsSuccessStatusCode && responseMessage2.IsSuccessStatusCode)
            {
                //sve tekstove smjesti u listu te
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;
                var Tekstovi = JsonConvert.DeserializeObject<List<Tekst>>(responseData);
                List<Tekst> te = await responseMessage.Content.ReadAsAsync<List<Tekst>>();

                // sve korisnike smjesti u listu ko
                var responseData1 = responseMessage1.Content.ReadAsStringAsync().Result;
                var Korisnici = JsonConvert.DeserializeObject<List<Korisnik>>(responseData1);
                List<Korisnik> ko = await responseMessage1.Content.ReadAsAsync<List<Korisnik>>();

                // sve komentare smjesti u listu comm
                var responseData2 = responseMessage2.Content.ReadAsStringAsync().Result;
                var Komentari = JsonConvert.DeserializeObject<List<Komentar>>(responseData2);
                List<Komentar> comm = await responseMessage2.Content.ReadAsAsync<List<Komentar>>();

                brojkomentara = comm.Count;
                brojkorisnika = ko.Count;
                brojtekstova = te.Count;

                ln.Add("Komentari");
                br.Add(brojkomentara);
                ln.Add("Korisnici");
                br.Add(brojkorisnika);
                ln.Add("Tekstovi");
                br.Add(brojtekstova);

            }
            
           
            IEnumerable<String> nazivi = ln.ToList();
            IEnumerable<int> brojke = br.ToList();

            var key = new Chart(width: 550, height: 350)

            .AddTitle("Broj tekstova, komentara i korisnika")
            .AddSeries(
                "Default", 
                chartType: "Pie",
                // legend: "Rainfall",                
                xValue: nazivi, 
                yValues: brojke)

            .Write();


            return null;
        }

        //akcija - dijagram broj komentara po korisniku!
        public async Task<ActionResult> KomentarDijagram()
        {

            string url1 = "http://localhost:3106/api/korisnik";
            HttpResponseMessage responseMessage1 = await client.GetAsync(url1); // pokupi sve korisnike
            string url2 = "http://localhost:3106/api/komentar";
            HttpResponseMessage responseMessage2 = await client.GetAsync(url2); // pokupi sve komentare
            List<LaraKlasa> lara = new List<LaraKlasa>();
            List<String> korisnickoIme = new List<String>();
            List<int> brojKomentara = new List<int>();

NWTServis/TextITMVC/Views/Tekst/Create.cshtml
@model ServisTextIT.Models.Tekst

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<div ng-controller="TekstAdd">
    
    <br />
    <table>
        <tr>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td><label style="visibility:hidden">ID</label></td>
            <td><input ng-model="tekst.id" style="visibility:hidden" /></td>
        </tr>
        <tr>
            <td><label>Naslov</label></td>
            <td><input ng-model="tekst.naslov" style="width:10000px"/></td>
        </tr>
        <tr>
            <td><label>Sadrzaj</label></td>
            <td><input ng-model="tekst.sadrzaj" style="width:10000px; height:200px"/></td>
        </tr>
        <tr>
            <td><label>Link</label></td>
            <td><input ng-model="tekst.link" style="width:10000px" /></td>

        </tr>
        <tr>
            <td><label style="visibility:hidden">Like</label></td>
            <td><input ng-model="tekst.like" style="visibility:hidden"/></td>
        </tr>
        <tr>
            <td><label style="visibility:hidden">datumObjave</label></td>
            <td><input ng-model="tekst.datumObjave" style="visibility:hidden" /></td>
        </tr>
        <tr>
            <td><label style="visibility:hidden">korisnikID</label></td>
            <td><input ng-model="tekst.korisnikID" style="visibility:hidden" /></td>
        </tr>


    </table>
    <button type="button" ng-click="addTekst('@Model.tekstID')" class="btn btn-primary btn-large" ng-model="dodaj">Dodaj tekst</button>


</div>

NWTServis/TextITMVC/Views/Tekst/Dijagram.cshtml
@{
    ViewBag.Title = "Dijagram";
}

<h2 style="color:ghostwhite; align-items:center">Statistika</h2>
<hr/>
<br />
<br />
<br />
<div align="left">
    <h4 style="color:ghostwhite">Broj tekstova po korisniku</h4>
    <div align="left">
        <img src="@Url.Action("KorisnikBrojTekstova", "Tekst")" alt="cricketers" />
    </div>
</div>
<br />
<br />
    <div align="right">
        <h4 style="color:ghostwhite">Broj tekstova, korisnika i komentara</h4>
        <div align="right">
            <img src="@Url.Action("PitaDijagram", "Tekst")" alt="cricketers" />
        </div>
    </div>
<br />
<br />
    <div align="left">
        <h4 style="color:ghostwhite">Broj komentara po korisniku</h4>
        <div align="left">
            <img src="@Url.Action("KomentarDijagram", "Tekst")" alt="cricketers" />
        </div>
    </div>
<br />
<br />
<div align="right">
    <h4 style="color:ghostwhite">Broj administratora i korisnika</h4>
    <div align="right">
        <img src="@Url.Action("PitaDijagramAdminUser", "Tekst")" alt="cricketers" />
    </div>
</div>
<br />
<br />
<div align="left">
    <h4 style="color:ghostwhite">Broj komentara po mjesecu</h4>
    <div align="left">
        <img src="@Url.Action("KomentarMjesecDijagram", "Tekst")" alt="cricketers" />
    </div>
</div>
<br />
<br />
<div align="right">
    <h4 style="color:ghostwhite">Broj različitih e-mail adresa korisnika</h4>
    <div align="right">
        <img src="@Url.Action("PitaDijagramMail", "Tekst")" alt="cricketers" />
    </div>
</div>
<br />
<br />
<div align="left">
    <h4 style="color:ghostwhite">Broj tekstova po godinama</h4>
    <div align="left">
        <img src="@Url.Action("TekstGodinaDijagram", "Tekst")" alt="cricketers" />
    </div>
</div>
<br />
<br />
<div align="right">
    <h4 style="color:ghostwhite">Broj tekstova po mjesecu</h4>
    <div align="right">
        <img src="@Url.Action("TekstMjesecDijagram", "Tekst")" alt="cricketers" />
    </div>
</div>

NWTServis/TextITMVC/Views/Tekst/Edit.cshtml
@model ServisTextIT.Models.Tekst

@{
    ViewBag.Title = "Edit";
}

<h2>Izmijeni</h2>


<h4>Tekst</h4>
<hr />

<div ng-controller="TekstEdit" data-ng-init="editTekst('@Model.tekstID')">
    <table>
        <tr>
            <td><label style="visibility:hidden">ID</label></td>
            <td><input ng-model="tekst.id" style="visibility:hidden" /></td>
        </tr>
        <tr>
            <td><label>Naslov</label></td>
            <td><input placeholder="naslov" ng-model="tekst.naslov" style="width:10000px" /></td>
        </tr>
        <tr>
            <td><label>Sadrzaj</label></td>
            <td><input ng-model="tekst.sadrzaj" style="width:10000px; height:200px" /></td>
        </tr>
        <tr>
            <td><label>Link</label></td>
            <td><input ng-model="tekst.link" style="width:10000px"/></td>
        </tr>
        <tr>
            <td><label style="visibility:hidden">Like</label></td>
            <td><input ng-model="tekst.like" style="visibility:hidden"/></td>
        </tr>
        <tr>
            <td><label style="visibility:hidden">Korisnik</label></td>
            <td><input ng-model="tekst.korisnikID" style="visibility:hidden" /></td>
        </tr>


    </table>
    <button type="button" ng-click="updateTekst('@Model.tekstID')" class="btn btn-primary btn-large" ng-model="izmijeni">Izmijeni</button>
</div>

NWTServis/TextITMVC/Views/Tekst/Index.cshtml
@model IEnumerable<ServisTextIT.Models.Tekst>

@{
    ViewBag.Title = "Index";
}





<h1>Tekstovi</h1>
<div ng-controller="Tekstovi" data-ng-init="getTekst()">
    <button>
       
        <div>
            @Html.ActionLink("Dodaj Tekst", "Create")
        </div>
    </button>
    <br />
    <div title="Tekstovi">

        <hr />
        <div ng-repeat="tekst in tekstovi">
            <label>{{tekst.naslov}}</label>
            <p ng-model="tekst">{{tekst.sadrzaj}}</p>
            <p ng-model="tekst">{{tekst.datumObjave}}</p>
            <table class="table">
                <tr>
                    <td>
                        <button type="button" ng-click="deleteTekst(tekst)" class="btn btn-primary btn-large" ng-model="tekst.tekstID">Obriši!</button>
                    </td>
                    <td align="right">
                        <button type="button" ng-click="editTekst(tekst)" class="btn btn-primary btn-large" ng-model="tekst.tekstID">Izmijeni</button>
                    </td>

                </tr>
            </table>
        </div>
    </div>
</div>